baseURL: https://nicolasfriedli.ch
title: Nicolas Friedli

languageCode: fr-ch
defaultContentLanguage: fr

canonifyURLs: true
disableFastRender: true

disableKinds:
  - taxonomy
  - taxonomyTerm


menu:
  maiaaaaan:
    - title: Flux RSS
      url: /index.xml
      weight: 990

params:
  slogan: consultant web indépendant
  footer : |
    Sauf mention contraire, les contenus de ce site sont publiés sous licence CC by-sa.

pygmentsCodeFences: true
pygmentsStyle: monokai

markup:
  defaultMarkdownHandler: goldmark