baseURL: https://nicolasfriedli.ch
title: Nicolas Friedli

languageCode: fr-ch
defaultContentLanguage: fr

canonifyURLs: true
copyright: Creative Commons by-sa
disableFastRender: true
enableGitInfo: true
cleandestinationdir: true
removePathAccents: true

author:
  name: Nicolas Friedli
  email: nicolasfriedli@protonmail.ch

disableKinds:
  - taxonomy
  - term
  - robotsTXT

imaging:
  resampleFilter: lanczos
  quality: 80
  bgColor: ffffff
  exif: 
    includeFields: ".*"

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      typographer: true
    parser:
      autoHeadingIDType: github-ascii
    renderer:
      unsafe: true
  highlight:
    style: monokai
    noClasses: false

params:
  title: Nicolas Friedli
  slogan: consultant web indépendant
  images: 
    - https://cdn.pixabay.com/photo/2012/12/19/18/12/scrapyard-70908_960_720.jpg
  footer : |
    **S'abonner:** [Flux RSS](/index.xml "S'abonner au site par flux RSS")   
    **Se renseigner:** [À propos de ce site](/about/ "Informations techniques et rédactionnelles") & [Contact](/contact/ "Contacter Nicolas Friedli")  
    **Naviguer:** [Plan](/plan/ "Plan complet du site de Nicolas Friedli") & [Liens](/links/ "Quelques liens qui comptent aux yeux de l'auteur du site")