baseURL: https://nicolasfriedli.ch
title: Nicolas Friedli

languageCode: fr-ch
defaultContentLanguage: fr

canonifyURLs: true
disableFastRender: true

disableKinds:
  - taxonomy
  - taxonomyTerm

params:
  slogan: consultant web indépendant
  footer : |
    Sauf mention contraire, les contenus de ce site sont publiés sous licence CC by-sa.

pygmentsCodeFences: true
pygmentsStyle: colorful

markup:
  defaultMarkdownHandler: goldmark