baseURL = "https://nicolasfriedli.ch/"
title = "Nicolas Friedli"

locale = "fr"
defaultContentLanguage = "fr"

removePathAccents = true

disableKinds = [ "taxonomy", "term", "robotsTXT"]

cleanDestinationDir = true
enableGitInfo = true
noBuildLock = true

copyright = "Creative Commons BY-SA"

[build]
writeStats = false

[frontmatter]
date = [":filename", "date", "lastmod", ":git"]
lastmod = ["lastmod", "date", ":git"]

[markup]
[markup.goldmark.parser]
autoHeadingIDType = "github-ascii"

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.tableOfContents]
endLevel = 6

# Menu

[menus]

[[menus.main]]
pageRef = "/"
weight = 10

[[menus.main]]
pageRef = "/blog"
weight = 20

[[menus.main]]
pageRef = "/contact"
weight = 30

# Fin menu

[minify]
minifyOutput = true

[minify.tdewolff.html]
keepDefaultAttrVals = false
keepQuotes = true
keepWhitespace = true

[params]
images = ["/images/opengraph.jpg"]

[params.author]
name = "Nicolas Friedli"
email = "hello+rss@nicolasfriedli.ch"

[services]
[services.rss]
limit = 20